In [13]:
import pandas as pd
import numpy as np
import pickle

In [14]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [15]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([1, 'male', 35.0, 0, 0, 512.3292, 'C'],dtype=object).reshape(1,7)

In [16]:
test_input

array([[1, 'male', 35.0, 0, 0, 512.3292, 'C']], dtype=object)

In [17]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [18]:
test_input_sex

array([[0., 1.]])

In [19]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [20]:
test_input_embarked

array([[1., 0., 0.]])

In [21]:
test_input_age = test_input[:,2].reshape(1,1)

In [22]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [23]:
test_input_transformed.shape

(1, 10)

In [24]:
clf.predict(test_input_transformed)

array([1], dtype=int64)